server:
  port: 8082

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://ep-damp-sea-a1g2d237-pooler.ap-southeast-1.aws.neon.tech/user-service?sslmode=require&channel_binding=require
    username: user-service
    password: npg_oEmj4RQI0Nxl
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    com.wanafiq.userservice: DEBUG
    org.springframework.security: DEBUG
    org.hibernate: DEBUG
    com.netflix.discovery.*: DEBUG

app:
  security:
    auth-server:
      jwk-set-uri: http://localhost:8081/oauth2/jwks
